-- INSERT INTO package_details (id, sendername, recipientname, item, fare, address_locality, city, pincode, order_id, phonenumber,pick_up_address, drop_off_address) VALUES (1, 'Vusi Ndaba', 'Lorcan Chabalala', 'Tupperware', 200.00, 'Rosslyn', 'Pretoria', 0201, 'oder0001', '0790789235', 'karen Park', 'Rosslyn');
-- INSERT INTO package_details (id, sendername, recipientname, item, fare, address_locality, city, pincode, order_id, phonenumber,pick_up_address, drop_off_address) VALUES (2, 'Duncan Williams', 'Fumani Ted', 'Coffee Table', 500.00, 'Chiawelo', 'Pretoria', 0200, 'oder0002', '07601425235', 'DiepKloof', 'Chiawelo');
-- INSERT INTO package_details (id, sendername, recipientname, item, fare, address_locality, city, pincode, order_id, phonenumber,pick_up_address, drop_off_address) VALUES (3, 'Steve Dlomo', 'Esihle M', 'laptop', 350.00, 'Hatfield', 'Protea Glen', 0280, 'oder0003', '0710727712', 'Lawley', 'Protea Glen');
-- INSERT INTO package_details (id, sendername, recipientname, item, fare, address_locality, city, pincode, order_id, phonenumber,pick_up_address, drop_off_address) VALUES (4, 'Faith Richards', 'Ellen Rand', 'Phone', 280.00, 'Midrand', 'Pretoria', 0291, 'oder0004', '0724562020', 'centurion', 'Midrand');
-- INSERT INTO package_details (id, sendername, recipientname, item, fare, address_locality, city, pincode, order_id, phonenumber,pick_up_address, drop_off_address) VALUES (5, 'Rich Davula', 'Joy Swangs', 'Documents', 240.00, 'Centurion', 'Pretoria', 0220, 'oder0005', '0785199295', 'Arcadia', 'Centurion');
-- INSERT INTO package_details (id, sendername, recipientname, item, fare, address_locality, city, pincode, order_id, phonenumber,pick_up_address, drop_off_address) VALUES (6, 'Sophie Nkuna', 'Nhlanhla King', 'Shoes', 350.00, 'Joubert Park', 'Johannesburg', 1818, 'oder0006', '0763356231', 'Lenasia', 'Doornfontein');
-- INSERT INTO package_details (id, sendername, recipientname, item, fare, address_locality, city, pincode, order_id, phonenumber,pick_up_address, drop_off_address) VALUES (7, 'Teddy Mthombeni', 'Levi Smith', 'Smart TV', 40.00, 'Rooderport', 'Johannesburg', 1795, 'oder0007', '072056243', 'Naturena', 'Rooderport');
-- INSERT INTO package_details (id, sendername, recipientname, item, fare, address_locality, city, pincode, order_id, phonenumber,pick_up_address, drop_off_address) VALUES (8, 'Hlomani Maluleke', 'Thami Magwaza', 'Microwave', 300.00, 'Orchards', 'Pretoria', 1254, 'oder0008', '0760354465', 'Soshanguve', 'Orchards');


